# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: 1.11
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: cd Pathfinding && chmod +x gradlew
    - name: Test with Gradle
      run: cd Pathfinding && ./gradlew test
    - name: Code coverage rapost
      run: cd Pathfinding && ./gradlew jacocoTestReport
    - name: Data to codecov
      run: cd Pathfinding && bash <(curl -s https://codecov.io/bash)
